<?php

namespace ContainerRIeVafb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LWw_98VService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LWw.98V' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LWw.98V'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rncp' => ['privates', '.errored..service_locator.LWw.98V.App\\Entity\\Rncp', NULL, 'Cannot autowire service ".service_locator.LWw.98V": it references class "App\\Entity\\Rncp" but no such service exists.'],
            'rncpRepository' => ['privates', 'App\\Repository\\RncpRepository', 'getRncpRepositoryService', true],
        ], [
            'rncp' => 'App\\Entity\\Rncp',
            'rncpRepository' => 'App\\Repository\\RncpRepository',
        ]);
    }
}
