<?php

namespace ContainerRIeVafb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRncpTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\RncpType' shared autowired service.
     *
     * @return \App\Form\RncpType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/RncpType.php';

        return $container->privates['App\\Form\\RncpType'] = new \App\Form\RncpType();
    }
}
