<?php

namespace ContainerRIeVafb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRncp2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cOSnBWz.App\Entity\Rncp' shared service.
     *
     * @return \App\Entity\Rncp
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.cOSnBWz": it references class "App\\Entity\\Rncp" but no such service exists.');
    }
}
