<?php

namespace ContainerUNzHt5m;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccueilService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.A45GxH5.App\Entity\Accueil' shared service.
     *
     * @return \App\Entity\Accueil
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.A45GxH5": it references class "App\\Entity\\Accueil" but no such service exists.');
    }
}
