<?php

namespace ContainerHz7pAsi;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EDFtQ_EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EDFtQ.E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EDFtQ.E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'accueilRepository' => ['privates', 'App\\Repository\\AccueilRepository', 'getAccueilRepositoryService', true],
        ], [
            'accueilRepository' => 'App\\Repository\\AccueilRepository',
        ]);
    }
}
