<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW4jVRPp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW4jVRPp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW4jVRPp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW4jVRPp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW4jVRPp\App_KernelDevDebugContainer([
    'container.build_hash' => 'W4jVRPp',
    'container.build_id' => '1fc74289',
    'container.build_time' => 1658485378,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW4jVRPp');
