<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRIeVafb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRIeVafb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRIeVafb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRIeVafb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRIeVafb\App_KernelDevDebugContainer([
    'container.build_hash' => 'RIeVafb',
    'container.build_id' => 'ff5eb3e0',
    'container.build_time' => 1658498411,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRIeVafb');
