<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT7fMRsJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT7fMRsJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT7fMRsJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT7fMRsJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerT7fMRsJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'T7fMRsJ',
    'container.build_id' => '91e88fdc',
    'container.build_time' => 1658761482,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT7fMRsJ');
