<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_accueil' => [[], ['_controller' => 'App\\Controller\\AccueilController::index'], [], [['text', '/accueil']], [], [], []],
    'app_admin_accueil_index' => [[], ['_controller' => 'App\\Controller\\AdminAccueilController::index'], [], [['text', '/admin/accueil/']], [], [], []],
    'app_admin_accueil_new' => [[], ['_controller' => 'App\\Controller\\AdminAccueilController::new'], [], [['text', '/admin/accueil/new']], [], [], []],
    'app_admin_accueil_show' => [['id'], ['_controller' => 'App\\Controller\\AdminAccueilController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/accueil']], [], [], []],
    'app_admin_accueil_edit' => [['id'], ['_controller' => 'App\\Controller\\AdminAccueilController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/accueil']], [], [], []],
    'app_admin_accueil_delete' => [['id'], ['_controller' => 'App\\Controller\\AdminAccueilController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/accueil']], [], [], []],
    'app_admin_dashboard' => [[], ['_controller' => 'App\\Controller\\AdminDashboardController::index'], [], [['text', '/']], [], [], []],
    'app_admin_rncp_index' => [[], ['_controller' => 'App\\Controller\\AdminRncpController::index'], [], [['text', '/admin/rncp/']], [], [], []],
    'app_admin_rncp_new' => [[], ['_controller' => 'App\\Controller\\AdminRncpController::new'], [], [['text', '/admin/rncp/new']], [], [], []],
    'app_admin_rncp_show' => [['id'], ['_controller' => 'App\\Controller\\AdminRncpController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/rncp']], [], [], []],
    'app_admin_rncp_edit' => [['id'], ['_controller' => 'App\\Controller\\AdminRncpController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/rncp']], [], [], []],
    'app_admin_rncp_delete' => [['id'], ['_controller' => 'App\\Controller\\AdminRncpController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/rncp']], [], [], []],
    'app_admin_team' => [[], ['_controller' => 'App\\Controller\\AdminTeamController::index'], [], [['text', '/admin/team']], [], [], []],
    'app_team' => [[], ['_controller' => 'App\\Controller\\TeamController::index'], [], [['text', '/team']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
];
